name: Autonomous Maintenance
on:
  schedule:
    - cron: '30 1 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale. It will be closed in 5 days if no activity occurs.'
          days-before-stale: 30
          days-before-close: 5
